# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\main.ui'
#
# Created: Mon Mar 14 16:53:01 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(565, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/icon-64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit_logging = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_logging.setObjectName(_fromUtf8("textEdit_logging"))
        self.gridLayout.addWidget(self.textEdit_logging, 3, 0, 1, 1)
        self.tableWidget_books = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_books.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableWidget_books.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_books.setAlternatingRowColors(True)
        self.tableWidget_books.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_books.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_books.setObjectName(_fromUtf8("tableWidget_books"))
        self.tableWidget_books.setColumnCount(5)
        self.tableWidget_books.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_books.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_books.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_books.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_books.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_books.setHorizontalHeaderItem(4, item)
        self.tableWidget_books.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_books.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_books, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_specialUrl = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_specialUrl.setObjectName(_fromUtf8("lineEdit_specialUrl"))
        self.horizontalLayout.addWidget(self.lineEdit_specialUrl)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUpdate = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/find_60.631578947368px_1148151_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate.setIcon(icon1)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionDownloadAll = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Download_73.119383825417px_1183408_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDownloadAll.setIcon(icon2)
        self.actionDownloadAll.setObjectName(_fromUtf8("actionDownloadAll"))
        self.actionOpenInBrowser = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/globe_search_63.667532467532px_1192123_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenInBrowser.setIcon(icon3)
        self.actionOpenInBrowser.setObjectName(_fromUtf8("actionOpenInBrowser"))
        self.actionOpenBooksFolder = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/folder_documents_64px_1072317_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenBooksFolder.setIcon(icon4)
        self.actionOpenBooksFolder.setObjectName(_fromUtf8("actionOpenBooksFolder"))
        self.actionPowe_OffAfterFinish = QtGui.QAction(MainWindow)
        self.actionPowe_OffAfterFinish.setCheckable(True)
        self.actionPowe_OffAfterFinish.setObjectName(_fromUtf8("actionPowe_OffAfterFinish"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionClean_Temp_Folder = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Delete_64px_1183403_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClean_Temp_Folder.setIcon(icon5)
        self.actionClean_Temp_Folder.setObjectName(_fromUtf8("actionClean_Temp_Folder"))
        self.actionRename_All = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/rename_64px_1125671_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_All.setIcon(icon6)
        self.actionRename_All.setObjectName(_fromUtf8("actionRename_All"))
        self.actionMerge = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/flow_merge_51.250996015936px_1158617_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMerge.setIcon(icon7)
        self.actionMerge.setObjectName(_fromUtf8("actionMerge"))
        self.actionCrop = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Crop_64px_1177465_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop.setIcon(icon8)
        self.actionCrop.setObjectName(_fromUtf8("actionCrop"))
        self.actionCrop_4print = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/print_73.226993865031px_1187925_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_4print.setIcon(icon9)
        self.actionCrop_4print.setObjectName(_fromUtf8("actionCrop_4print"))
        self.actionCrop_4kindle = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/kindle_64px_1099796_easyicon.net.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_4kindle.setIcon(icon10)
        self.actionCrop_4kindle.setObjectName(_fromUtf8("actionCrop_4kindle"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_list_view_in_browser = QtGui.QAction(MainWindow)
        self.action_list_view_in_browser.setObjectName(_fromUtf8("action_list_view_in_browser"))
        self.action_list_download = QtGui.QAction(MainWindow)
        self.action_list_download.setObjectName(_fromUtf8("action_list_download"))
        self.action_list_remove = QtGui.QAction(MainWindow)
        self.action_list_remove.setObjectName(_fromUtf8("action_list_remove"))
        self.action_list_merge = QtGui.QAction(MainWindow)
        self.action_list_merge.setObjectName(_fromUtf8("action_list_merge"))
        self.action_list_crop = QtGui.QAction(MainWindow)
        self.action_list_crop.setObjectName(_fromUtf8("action_list_crop"))
        self.action_list_rename = QtGui.QAction(MainWindow)
        self.action_list_rename.setObjectName(_fromUtf8("action_list_rename"))
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addAction(self.actionDownloadAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenInBrowser)
        self.menuFile.addAction(self.actionOpenBooksFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPowe_OffAfterFinish)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionClean_Temp_Folder)
        self.menuEdit.addAction(self.actionRename_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMerge)
        self.menuEdit.addAction(self.actionCrop)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCrop_4print)
        self.menuEdit.addAction(self.actionCrop_4kindle)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionUpdate)
        self.toolBar.addAction(self.actionDownloadAll)
        self.toolBar.addAction(self.actionOpenInBrowser)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenBooksFolder)
        self.toolBar.addAction(self.actionClean_Temp_Folder)
        self.toolBar.addAction(self.actionRename_All)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCrop)
        self.toolBar.addAction(self.actionMerge)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCrop_4print)
        self.toolBar.addAction(self.actionCrop_4kindle)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionUpdate, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_update)
        QtCore.QObject.connect(self.actionDownloadAll, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_download_all)
        QtCore.QObject.connect(self.actionOpenInBrowser, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_open_special_in_browser)
        QtCore.QObject.connect(self.actionOpenBooksFolder, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_open_books_folder)
        QtCore.QObject.connect(self.actionClean_Temp_Folder, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_clean_tmp_folder)
        QtCore.QObject.connect(self.actionRename_All, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_rename_all)
        QtCore.QObject.connect(self.actionCrop, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_crop_book)
        QtCore.QObject.connect(self.actionMerge, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_merge_book)
        QtCore.QObject.connect(self.actionCrop_4print, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_crop_4print)
        QtCore.QObject.connect(self.actionCrop_4kindle, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_crop_4kindle)
        QtCore.QObject.connect(self.actionPowe_OffAfterFinish, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.on_power_off_setting)
        QtCore.QObject.connect(self.action_list_view_in_browser, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_view_in_browser)
        QtCore.QObject.connect(self.action_list_download, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_download)
        QtCore.QObject.connect(self.action_list_remove, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_remove)
        QtCore.QObject.connect(self.action_list_merge, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_merge)
        QtCore.QObject.connect(self.action_list_crop, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_crop)
        QtCore.QObject.connect(self.action_list_rename, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.do_list_rename)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_add_book(int)")), self.tableWidget_books.insertRow)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_del_book(int)")), self.tableWidget_books.removeRow)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_special_url(QString)")), self.lineEdit_specialUrl.setText)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_logging(QString)")), self.textEdit_logging.append)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_status(QString)")), self.statusbar.showMessage)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("when_progress(int)")), self.progressBar.setValue)
        QtCore.QObject.connect(self.tableWidget_books, QtCore.SIGNAL(_fromUtf8("cellDoubleClicked(int,int)")), MainWindow.do_list_dclick)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("destroyed()")), MainWindow.do_destroyed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidget_books.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.tableWidget_books.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TITLE", None))
        item = self.tableWidget_books.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AUTHOR", None))
        item = self.tableWidget_books.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LINK", None))
        item = self.tableWidget_books.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PROGRESS", None))
        self.label.setText(_translate("MainWindow", "Secial Books", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionUpdate.setText(_translate("MainWindow", "Update", None))
        self.actionUpdate.setToolTip(_translate("MainWindow", "Update special list", None))
        self.actionDownloadAll.setText(_translate("MainWindow", "Download All", None))
        self.actionOpenInBrowser.setText(_translate("MainWindow", "Open In Browser", None))
        self.actionOpenInBrowser.setToolTip(_translate("MainWindow", "Open Special In Browser", None))
        self.actionOpenBooksFolder.setText(_translate("MainWindow", "Open Books Folder", None))
        self.actionPowe_OffAfterFinish.setText(_translate("MainWindow", "Power Off After Finish", None))
        self.actionPowe_OffAfterFinish.setToolTip(_translate("MainWindow", "Set Power Off After Finish", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionClean_Temp_Folder.setText(_translate("MainWindow", "Clean Temp Folder", None))
        self.actionRename_All.setText(_translate("MainWindow", "Rename All", None))
        self.actionMerge.setText(_translate("MainWindow", "Merge", None))
        self.actionCrop.setText(_translate("MainWindow", "Crop", None))
        self.actionCrop.setToolTip(_translate("MainWindow", "Crop a singal book", None))
        self.actionCrop_4print.setText(_translate("MainWindow", "Crop For Printing", None))
        self.actionCrop_4kindle.setText(_translate("MainWindow", "Crop For Kindle", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.action_list_view_in_browser.setText(_translate("MainWindow", "View In Browser", None))
        self.action_list_download.setText(_translate("MainWindow", "Download", None))
        self.action_list_remove.setText(_translate("MainWindow", "Remove", None))
        self.action_list_merge.setText(_translate("MainWindow", "Merge", None))
        self.action_list_crop.setText(_translate("MainWindow", "Crop", None))
        self.action_list_rename.setText(_translate("MainWindow", "Rename", None))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

